version: '3.8'

services:
  database:
    container_name: directus_database
    image: postgis/postgis:15-master
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-directus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-directus}
      POSTGRES_DB: ${DB_DATABASE:-directus}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-directus}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    container_name: directus_cache
    image: redis:7-alpine
    restart: unless-stopped

  directus:
    container_name: directus
    image: directus/directus:10.10.7
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      # General
      KEY: ${KEY}
      SECRET: ${SECRET}
      
      # Database
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE:-directus}
      DB_USER: ${DB_USER:-directus}
      DB_PASSWORD: ${DB_PASSWORD:-directus}
      
      # Cache
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      
      # Admin
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@instabids.ai}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      
      # Public URL
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8055}
      
      # Enable extensions auto-reload
      EXTENSIONS_AUTO_RELOAD: 'true'
      
      # Telemetry
      TELEMETRY: 'false'

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy/config:/config
    depends_on:
      - directus

volumes:
  database:
  uploads:
  extensions: